In [1]:
import numpy as np

In [2]:
arr = np.arange(1,10)

In [3]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr2 = arr.copy()
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
newArray = np.arange(1,21)

In [9]:
newArray

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [10]:
newArray.reshape(5,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [11]:
newArray = newArray.reshape(5,4)
newArray

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [22]:
newArray[:,:1]

array([[ 1],
       [ 5],
       [ 9],
       [13],
       [17]])

In [15]:
arr = np.arange(1,11)

In [16]:
print(arr>3)

[False False False  True  True  True  True  True  True  True]


In [17]:
booleanArray = arr>3


In [18]:
booleanArray

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [20]:
arr[booleanArray]

array([ 4,  5,  6,  7,  8,  9, 10])

In [21]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])